<?php

namespace Database\Seeders;

use App\Models\JenisBarangGadai;
use Illuminate\Database\Seeder;

class JenisBarangGadaiSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Laptop / Notebook',
                'category' => 'Elektronik',
                'description' => 'Laptop, notebook, atau ultrabook semua merek dan tipe',
                'base_value_per_unit' => 3000000,
                'unit' => 'unit',
                'max_loan_percentage' => 80,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Apple', 'value' => 12000000],
                    ['name' => 'Asus', 'value' => 5500000],
                    ['name' => 'HP', 'value' => 4500000],
                    ['name' => 'Lenovo', 'value' => 5000000],
                    ['name' => 'Acer', 'value' => 4000000],
                    ['name' => 'Axioo', 'value' => 2500000],
                ],
                'requirements' => ['Charger asli', 'Box (jika ada)', 'Catatan kondisi baterai'],
                'is_active' => true,
            ],
            [
                'name' => 'Smartphone / HP',
                'category' => 'Elektronik',
                'description' => 'Handphone, smartphone semua merek',
                'base_value_per_unit' => 1000000,
                'unit' => 'unit',
                'max_loan_percentage' => 80,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'iPhone', 'value' => 9000000],
                    ['name' => 'Samsung', 'value' => 5000000],
                    ['name' => 'Xiaomi', 'value' => 3000000],
                    ['name' => 'Oppo', 'value' => 3000000],
                    ['name' => 'Vivo', 'value' => 2800000],
                    ['name' => 'Realme', 'value' => 2200000],
                ],
                'requirements' => ['Charger asli', 'Box (jika ada)'],
                'is_active' => true,
            ],
            [
                'name' => 'TV / Televisi',
                'category' => 'Elektronik',
                'description' => 'Televisi LED, OLED, QLED semua ukuran',
                'base_value_per_unit' => 1500000,
                'unit' => 'unit',
                'max_loan_percentage' => 70,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Sony', 'value' => 4000000],
                    ['name' => 'Samsung', 'value' => 3500000],
                    ['name' => 'LG', 'value' => 3200000],
                    ['name' => 'Toshiba', 'value' => 2200000],
                    ['name' => 'Sharp', 'value' => 2000000],
                    ['name' => 'Polytron', 'value' => 1500000],
                ],
                'requirements' => ['Remote', 'Kabel power', 'Box (jika ada)'],
                'is_active' => true,
            ],
            [
                'name' => 'Kulkas / Lemari Es',
                'category' => 'Peralatan Rumah Tangga',
                'description' => 'Kulkas 1 pintu, 2 pintu, side by side',
                'base_value_per_unit' => 1000000,
                'unit' => 'unit',
                'max_loan_percentage' => 70,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Samsung', 'value' => 3500000],
                    ['name' => 'LG', 'value' => 3200000],
                    ['name' => 'Panasonic', 'value' => 2800000],
                    ['name' => 'Sharp', 'value' => 2300000],
                    ['name' => 'Aqua', 'value' => 1800000],
                    ['name' => 'Polytron', 'value' => 1500000],
                ],
                'requirements' => ['Kondisi kompresor baik', 'Tidak ada kebocoran freon'],
                'is_active' => true,
            ],
            [
                'name' => 'Rice Cooker / Magic Com',
                'category' => 'Peralatan Rumah Tangga',
                'description' => 'Rice cooker, magic com, magic jar',
                'base_value_per_unit' => 200000,
                'unit' => 'unit',
                'max_loan_percentage' => 70,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik'],
                'brands' => [
                    ['name' => 'Philips', 'value' => 600000],
                    ['name' => 'Panasonic', 'value' => 500000],
                    ['name' => 'Cosmos', 'value' => 350000],
                    ['name' => 'Yong Ma', 'value' => 300000],
                    ['name' => 'Maspion', 'value' => 250000],
                    ['name' => 'Miyako', 'value' => 220000],
                ],
                'requirements' => ['Sendok nasi', 'Kabel power', 'Berfungsi normal'],
                'is_active' => true,
            ],
            [
                'name' => 'Kompor Gas',
                'category' => 'Peralatan Rumah Tangga',
                'description' => 'Kompor gas tanam atau kompor portabel',
                'base_value_per_unit' => 300000,
                'unit' => 'unit',
                'max_loan_percentage' => 70,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik'],
                'brands' => [
                    ['name' => 'Modena', 'value' => 1200000],
                    ['name' => 'Rinnai', 'value' => 900000],
                    ['name' => 'Winn Gas', 'value' => 600000],
                    ['name' => 'Quantum', 'value' => 450000],
                    ['name' => 'Compos', 'value' => 350000],
                    ['name' => 'Miyako', 'value' => 300000],
                ],
                'requirements' => ['Tidak ada kebocoran', 'Nyala normal'],
                'is_active' => true,
            ],
            [
                'name' => 'Kipas Angin / AC',
                'category' => 'Peralatan Rumah Tangga',
                'description' => 'Kipas angin standing, atau AC split',
                'base_value_per_unit' => 300000,
                'unit' => 'unit',
                'max_loan_percentage' => 70,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Panasonic', 'value' => 800000],
                    ['name' => 'Sekai', 'value' => 600000],
                    ['name' => 'Cosmos', 'value' => 450000],
                    ['name' => 'Nagoya', 'value' => 400000],
                    ['name' => 'Maspion', 'value' => 350000],
                    ['name' => 'Miyako', 'value' => 280000],
                ],
                'requirements' => ['Berfungsi normal', 'Remote (untuk AC)'],
                'is_active' => true,
            ],
            [
                'name' => 'Perhiasan Emas',
                'category' => 'Perhiasan & Logam Mulia',
                'description' => 'Cincin, kalung, gelang, anting emas',
                'base_value_per_unit' => 1000000,
                'unit' => 'gram',
                'max_loan_percentage' => 85,
                'conditions' => ['24 Karat', '22 Karat', '18 Karat'],
                'brands' => [
                    ['name' => 'Kalung', 'value' => 1050000],
                    ['name' => 'Gelang', 'value' => 1020000],
                    ['name' => 'Cincin', 'value' => 980000],
                    ['name' => 'Liontin', 'value' => 950000],
                    ['name' => 'Anting', 'value' => 900000],
                ],
                'requirements' => ['Sertifikat (jika ada)', 'Berat dalam gram'],
                'is_active' => true,
            ],
            [
                'name' => 'Sepeda / Sepeda Listrik',
                'category' => 'Kendaraan & Transportasi',
                'description' => 'Sepeda gunung, sepeda road, sepeda lipat, atau sepeda listrik',
                'base_value_per_unit' => 500000,
                'unit' => 'unit',
                'max_loan_percentage' => 75,
                'conditions' => ['Baru', 'Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Polygon', 'value' => 3500000],
                    ['name' => 'United', 'value' => 1800000],
                    ['name' => 'Pacific', 'value' => 1200000],
                    ['name' => 'Wamcycle', 'value' => 900000],
                    ['name' => 'Exotic', 'value' => 700000],
                ],
                'requirements' => ['Kondisi rangka baik', 'Rem berfungsi', 'Tidak ada modifikasi ilegal'],
                'is_active' => true,
            ],
            [
                'name' => 'Motor / Sepeda Motor',
                'category' => 'Kendaraan & Transportasi',
                'description' => 'Sepeda motor bebek, matic, sport',
                'base_value_per_unit' => 5000000,
                'unit' => 'unit',
                'max_loan_percentage' => 80,
                'conditions' => ['Sangat Baik', 'Baik', 'Cukup'],
                'brands' => [
                    ['name' => 'Vixion', 'value' => 16000000],
                    ['name' => 'Vario', 'value' => 13000000],
                    ['name' => 'Beat', 'value' => 12000000],
                    ['name' => 'Scoopy', 'value' => 11000000],
                    ['name' => 'Supra', 'value' => 10000000],
                    ['name' => 'Jupiter', 'value' => 9000000],
                ],
                'requirements' => ['STNK asli', 'BPKB asli', 'KTP pemilik', 'Pajak tidak mati lebih dari 2 tahun'],
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            JenisBarangGadai::create($item);
        }
    }
}
